name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - RELEASE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bank-term-deposit-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bank-term-deposit-app:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user
            
            sudo docker stop bank-term-deposit-container || true
            sudo docker rm bank-term-deposit-container || true
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/bank-term-deposit-app:latest
            sudo docker run -d -p 5000:5000 --name bank-term-deposit-container ${{ secrets.DOCKER_HUB_USERNAME }}/bank-term-deposit-app:latest
